export function buildAetherViewProps(values) {
  const {
    APP_VERSION, Activity, AetherConfirmDialog, AlertTriangle, AnimatePresence, BUILD_VERSION, BookOpen, Check,
    ChevronLeft, ChevronRight, Clapperboard, Clock, Columns2, CommandPalette, Copy, DiscoveryGridSection,
    Download, Edit3, ExperienceCenterShell, ExternalLink, Eye, FAVORITES_PLAYLIST_ID, FAVORITES_PLAYLIST_NAME, FastForward,
    FullPlaylistOverlay, FullQueueOverlay, Globe, Hand, HardDrive, HeaderSearchBox, HeaderSleepTimerControls, HealthMetricCard,
    Heart, Layers, ListMusic, Loader2, Lock, Maximize2, MessageSquare, Minimize2,
    MinusCircle, MixtapeVaultContent, Monitor, MotionConfig, Music, OfflineAvailablePanel, PartyMode, Pause,
    Play, PlaybackProgressIsland, PlayerActionButtons, PlayerModePill, PlayerTransportControls, Plus, PlusCircle, QueueBufferHeader,
    RefreshCw, Repeat, Rewind, RotateCcw, Save, Search, SecondaryNowPlayingStrip, Shuffle,
    Signal, SlidersHorizontal, Sparkles, StudioLibraryOverlayIsland, ToastPortal, Trash2, Upload, Users,
    Volume2, X, YouTubeAuthOverlay, Zap, activeLyricIndex, aetherProfile, alphaHex, appendManualLyricsDraftLine,
    appendRecentEvent, appendStampedManualLyricsLine, applyStoragePolicy, auraCardBorder, auraCardShadow, auraFieldStyle, auraPanelBorder, auraPanelShadow,
    auraPreset, auraStageDurationMs, auraStagePulseScale, autoplayMenuButtonRef, autoplayMenuStyle, autoplayMoodMode, avatarFileInputRef, beatRingsRef,
    cameraHandSignal, canAddPendingToVault, canDownloadCurrentTrack, canOpenCurrentSource, canUseUpdater, cassetteSide, catDoodlePeek, chromeTopOffset,
    clamp01, cleanQueueBuffer, clearAllDownloadedTracks, clearDiagnosticEvents, clearDiscoveryResults, clearSearchHistoryForScope, closeDestructiveConfirmation, closeHeaderSurfaces,
    closeLibraryOverlay, closeTipsOverlay, commandPaletteCommands, commandPaletteShortcutLabel, compactLyric, cookieAssuranceLine, cookieStatusLabel, cookieStatusTone,
    cookieSummaryLine, copyManualLyricsToClipboard, copyProfileLink, copyProfileShareCard, copySpotifyImportDebugLog, copyVaultSceneEmbed, currentManualLyricsLines, currentTrack,
    currentTrackSourceUrl, currentTrackTitle, cycleRepeatMode, desktopTopInsetClass, destructiveConfirmRequest, diagnosticPathBlockClass, diagnostics, diagnosticsApiBase,
    diagnosticsTopOffset, discardSearchHistoryItem, discordPrivate, discoveryItems, discoveryModeLabel, dismissRuntimeIssuePrompt, doodleIntensityBadge, doodleIntensityScale,
    downloadLabelById, downloadedTracks, draggedPlaylistName, draggedQueueIndex, dualVisualStageWidth, dualVisualStageZClass, engineStatus, exitVideoMode,
    expandedActiveRef, expandedContainerRef, experienceCenterInitialPage, faceControlSignal, faceControlStatus, faceVideoRef, favoriteInspectPlaylist, favoriteTracksList,
    ffmpegDetailLine, ffmpegStatusLabel, ffmpegStatusTone, flashLastAdded, focusedVaultName, focusedVaultTracks, focusedVaultVisibleTracks, formatBytes,
    formatDiagTime, formatManualLyricsTimestamp, formatTime, gestureNotice, getActivePlaybackPositionMs, getInspectSourceUrl, getProxyUrl, getTrackAddedMs,
    getTrackLastListenedMs, getTrackPlayCount, globalMediaShortcutsEnabled, handleAdd, handleAddToPlaylist, handleAttemptFixes, handleAvatarFileSelected, handleCleanVault,
    handleControl, handleCopyDiagnosticsValue, handleCopyPhrase, handleDeletePlaylist, handleDisableLock, handleDownloadCurrentTrack, handleDownloadMissingForVault, handleEnableLock,
    handleExportVault, handleFavoriteAddAll, handleFavoritePlayAll, handleGenerateRecoveryPhrase, handleGenerateSmartMix, handleHeaderDoubleClick, handleImportCookies, handleImportLocalMedia,
    handleImportSpotifyPlaylist, handleImportVault, handleLyricLineSeek, handleOfflineLibrarySearch, handlePlaylistAddAll, handlePlaylistPlayAll, handleRemove, handleRemoveFromPlaylist,
    handleRemoveTrackEverywhere, handleRemoveTrackFromPlaylist, handleRenamePlaylist, handleRepairEnvironment, handleResetLyricPreset, handleResetPlaybackEngine, handleResyncLyrics, handleRunInstaller,
    handleRunRuntimeRepair, handleSaveLyricPreset, handleSaveManualLyrics, handleSearch, handleSeek, handleSetSleepTimer, handleSync, handleToggleTouchIdLock,
    handleUpdateAction, handleVisualStagePointerActivity, handleVolumeChange, hasActiveSearchState, hasCompletedSearch, hasLyricPreset, headerAccentButtonClass, headerIconButtonClass,
    headerSearchInputRef, immersiveBeatIntensity, importReview, inferToastTone, inspectDurationMs, inspectPlaylistArtistCount, inspectPlaylistDurationMs, inspectPlaylistName,
    inspectPlaylistQueuedCount, inspectPlaylistSignal, inspectPlaylistTracklistText, inspectPlaylistTracks, inspectPrimaryTrack, inspectQueueIndex, inspectSourceUrl, inspectTarget,
    inspectTrack, inspectVaultNames, isAudioBuffering, isAuraMode, isAuraStageOpen, isAutoScrollPaused, isAutoplayEnabled, isAutoplayMenuOpen,
    isCameraPreviewVisible, isCommandPaletteOpen, isDepthMotionEnabled, isDiagnosticsOpen, isDoodleMode, isDownloadingTrack, isDualLayoutLocked, isDualVisualMode,
    isDualWorkspaceMode, isExperienceCenterOpen, isFaceControlEnabled, isFocusedMode, isFullDiscoveryContentReady, isFullPlaylistContentReady, isFullQueueContentReady, isGestureControlEnabled,
    isImmersiveLyricsLocked, isInspectPlaylistFromVault, isLibraryOverlayOpen, isLocalMediaImporting, isLockBusy, isLockModalOpen, isLyricPresetSaved, isLyricsExpanded,
    isLyricsLoading, isMacPlatform, isManualLyricsEditorOpen, isManualLyricsRawEditorOpen, isManualLyricsSaving, isManualLyricsTapMode, isMixtapeVaultContentReady, isMixtapeVaultOpen,
    isOfflineDownloadsBusy, isOfflineMode, isOfflineRemovalBusy, isPartyModeOpen, isPlayerOverlayOpen, isPlaying, isPlaylistInspect, isProfilePublishing,
    isQualityDropdownOpen, isRenamingPlaylist, isRuntimeRepairing, isSearchActive, isSearching, isSharedSceneOpen, isShortcutSettingsSaving, isSpotifyImportOpen,
    isSpotifyImporting, isStandalone, isStorageBusy, isTipsOverlayOpen, isTrackFavorite, isUpdateBusy, isVaultCleaning, isVaultImporting,
    isVerticalStack, isVideoReady, isViewingFavorites, isViewingFullDiscovery, isViewingFullPlaylist, isViewingFullQueue, lastAdded, leftWorkspaceClass,
    libraryActionTarget, libraryBrowseMode, libraryFilter, libraryInsights, libraryModeOptions, libraryOverlayCreateInputRef, libraryPlaylistFilterOptions, libraryPlaylistSortOptions,
    librarySearchNeedle, librarySearchTerm, librarySongFilter, librarySongFilterOptions, librarySongSort, librarySongSortOptions, librarySort, libraryTrackSort,
    libraryVisiblePlaylistNames, libraryVisibleSongEntries, livePulseReadout, loadManualLyricsFromRawText, localAudioRef, localVideoRef, lockDisablePassword, lockError,
    lockIdleMinutes, lockPasswordConfirm, lockPasswordInput, lockRecoveryStatus, lockRecoveryStatusError, lockStatus, lockUseTouchId, lyricOffsetMs,
    lyricPresetActionLabel, lyrics, lyricsContainerRef, lyricsHeaderEyebrow, lyricsListClass, lyricsPanelHeightClass, lyricsViewportClass, manualLyricsDraft,
    manualLyricsDraftError, manualLyricsRawText, manualLyricsSavedNotice, memoizedLyricsContent, mixtapeDurationMs, mixtapeEnergyPct, mixtapeLiveLyric, mixtapePositionMs,
    mixtapeProgressPct, mixtapePulse, mixtapePulseReadout, mixtapeSpectrum, mixtapeVaultRef, motion, movePlaylist, musicImportProvider,
    musicImportTheme, newPlaylistName, nextLyric, normalizeQueueTrack, normalizeTrackIdentity, oauthPrompt, offlineAvailableTracks, offlineDownloads,
    offlineLibrarySearchTerm, offlineVisibleTracks, openAppLockSettings, openDiagnosticsPage, openFeedbackPanel, openGestureLab, openLibraryOverlay, openManualLyricsEditor,
    openMusicImport, openPlaylistInspect, openSharedSceneInAether, openShortcutSettings, openSignalLedger, openTipsOverlay, openTrackInspect, orderedPlaylistNames,
    panelGlassClass, panelHeaderClass, panelInteractiveClass, parseInt, parseManualLyricsTimestamp, pasteCurrentLyricsIntoRawEditor, pendingLibraryItems, performanceMode,
    phraseBusy, phraseCopied, phraseGenerated, platform, playButtonRef, playDownloadedOnly, playInspectPlaylist, playSharedSceneInBrowser,
    playbackModeLabel, playerCardClass, playerTitleClass, playlists, profileStats, publishAetherProfile, pulseCanvasRef, qualityDropdownRef,
    queue, queueInspectPlaylist, queuePollDisplay, queuePollTime, refreshLockRecoveryStatus, refreshLockStatus, refreshOfflineDownloads, refreshStorageEstimate,
    refreshStorageStats, removeDownloadedById, removeManualLyricsDraftLine, renameValue, reorderPlaylistByDrag, reorderQueueByDrag, repairActionLabel, repairResult,
    repeatMode, repeatModeBadge, repeatModeLabel, requestDestructiveConfirmation, resetConfirmationSkipPrefs, resetShortcutSettingsToDefaults, resolveWarmupTrackId, rootModeClass,
    runAfterInputPaint, runStorageOptimize, runtimeIssuePrompt, saveProfileShareCard, saveShortcutSettings, searchHistoryByScope, searchQuery, searchResults,
    seekActivePlaybackTo, sessionRestoreNotice, setAetherProfile, setAuraPreset, setAutoplayMoodMode, setDiscordPrivate, setDraggedPlaylistName, setDraggedQueueIndex,
    setExperienceCenterInitialPage, setGlobalMediaShortcutsEnabled, setImportReview, setInspectTarget, setIsAppLocked, setIsAuraStageOpen, setIsAutoScrollPaused, setIsAutoplayEnabled,
    setIsAutoplayMenuOpen, setIsCameraPreviewVisible, setIsCommandPaletteOpen, setIsCreatingPlaylist, setIsDepthMotionEnabled, setIsDiagnosticsOpen, setIsDoodleMode, setIsExperienceCenterOpen,
    setIsFaceControlEnabled, setIsFocusedMode, setIsGestureControlEnabled, setIsLockModalOpen, setIsLyricsExpanded, setIsManualLyricsEditorOpen, setIsManualLyricsRawEditorOpen, setIsManualStop,
    setIsMixtapeVaultOpen, setIsOfflineMode, setIsPartyModeOpen, setIsPlayerOverlayOpen, setIsPlaying, setIsQualityDropdownOpen, setIsRenamingPlaylist, setIsSharedSceneOpen,
    setIsSpotifyImportOpen, setIsVerticalStack, setIsVideoReady, setIsViewingFullDiscovery, setIsViewingFullPlaylist, setIsViewingFullQueue, setLastAdded, setLibraryBrowseMode,
    setLibraryFilter, setLibrarySearchTerm, setLibrarySongFilter, setLibrarySongSort, setLibrarySort, setLibraryTrackSort, setLockDisablePassword, setLockIdleMinutes,
    setLockPasswordConfirm, setLockPasswordInput, setLockUseTouchId, setLyricOffsetMs, setManualLyricsRawText, setMusicImportProvider, setNewPlaylistName, setOauthPrompt,
    setOfflineLibrarySearchTerm, setPartyInfo, setPerformanceMode, setQueue, setRenameValue, setSearchQuery, setShortcutDraft, setShortcutSettingsError,
    setShowShortcutHints, setSkipEvents, setSleepCustomMinutes, setSleepFadeEnabled, setSpotifyImportLogs, setSpotifyImportPlaylistName, setSpotifyImportProgress, setSpotifyImportUrl,
    setStopAfterTrack, setStoragePolicy, setTipsDontShowAgain, setVideoMode, setVideoQuality, setViewingPlaylist, setVisualControlsPinned, setVisualVideoFit,
    setVisualizerMode, setWebAudioUnlocked, sharedModalCloseButtonClass, sharedScene, sharedSceneCanPlay, shortcutDraft, shortcutLabel, shortcutSettingsError,
    shortcuts, showFavoriteLibraryCard, showImmersiveLyricsOverlay, showSecondaryColumn, showShortcutHints, showVisualLyricOverlay, showVisualStage, showWindowsHeaderWindowControls,
    showWindowsTitleStrip, skipEvents, skipReasonToast, sleepCustomMinutes, sleepDeadline, sleepFadeEnabled, sleepRemainingStr, sleepTimerControlsRef,
    sleepTimerValue, soundLedgerView, spotifyImportLogs, spotifyImportPlaylistName, spotifyImportProgress, spotifyImportUrl, stampManualLyricsDraftLine, stopAfterTrack,
    storageEstimate, storagePolicy, storageStats, switchVideoMode, systemStats, themeColor, tipsDontShowAgain, toReadableShortcut,
    toggleFavoriteTrack, toggleWindowMaximize, topHeaderClass, trackControlAccent, trackControlGlow, trackHasSavedLyrics, trackProgressAccent, trackProgressGlow,
    unpublishAetherProfile, updateActionLabel, updateInfo, updateManualLyricsDraftLine, updateToast, vaultPulse, videoMode, videoQuality,
    viewingPlaylist, visualControlsPinned, visualLyricOverlayBottomClass, visualStageFooterVisible, visualStageHeaderVisible, visualStageLyric, visualStageNextLyric, visualStageTitle,
    visualStageTitleMarquee, visualVideoFit, visualizerCanvasRef, visualizerMode, volume, volumeToast, webAudioUnlocked, workspaceModeLabel,
    youtubeAuthRequiredRef, youtubePlayerRef, ytDlpDetailLine, ytDlpStatusLabel, ytDlpStatusTone,
  } = values;

  return {
  APP_VERSION,
  Activity,
  AetherConfirmDialog,
  AlertTriangle,
  AnimatePresence,
  BUILD_VERSION,
  BookOpen,
  Check,
  ChevronLeft,
  ChevronRight,
  Clapperboard,
  Clock,
  Columns2,
  CommandPalette,
  Copy,
  DiscoveryGridSection,
  Download,
  Edit3,
  ExperienceCenterShell,
  ExternalLink,
  Eye,
  FAVORITES_PLAYLIST_ID,
  FAVORITES_PLAYLIST_NAME,
  FastForward,
  FullPlaylistOverlay,
  FullQueueOverlay,
  Globe,
  Hand,
  HardDrive,
  HeaderSearchBox,
  HeaderSleepTimerControls,
  HealthMetricCard,
  Heart,
  Layers,
  ListMusic,
  Loader2,
  Lock,
  Maximize2,
  MessageSquare,
  Minimize2,
  MinusCircle,
  MixtapeVaultContent,
  Monitor,
  MotionConfig,
  Music,
  OfflineAvailablePanel,
  PartyMode,
  Pause,
  Play,
  PlaybackProgressIsland,
  PlayerActionButtons,
  PlayerModePill,
  PlayerTransportControls,
  Plus,
  PlusCircle,
  QueueBufferHeader,
  RefreshCw,
  Repeat,
  Rewind,
  RotateCcw,
  Save,
  Search,
  SecondaryNowPlayingStrip,
  Shuffle,
  Signal,
  SlidersHorizontal,
  Sparkles,
  StudioLibraryOverlayIsland,
  ToastPortal,
  Trash2,
  Upload,
  Users,
  Volume2,
  X,
  YouTubeAuthOverlay,
  Zap,
  activeLyricIndex,
  aetherProfile,
  alphaHex,
  appendManualLyricsDraftLine,
  appendRecentEvent,
  appendStampedManualLyricsLine,
  applyStoragePolicy,
  auraCardBorder,
  auraCardShadow,
  auraFieldStyle,
  auraPanelBorder,
  auraPanelShadow,
  auraPreset,
  auraStageDurationMs,
  auraStagePulseScale,
  autoplayMenuButtonRef,
  autoplayMenuStyle,
  autoplayMoodMode,
  avatarFileInputRef,
  beatRingsRef,
  cameraHandSignal,
  canAddPendingToVault,
  canDownloadCurrentTrack,
  canOpenCurrentSource,
  canUseUpdater,
  cassetteSide,
  catDoodlePeek,
  chromeTopOffset,
  clamp01,
  cleanQueueBuffer,
  clearAllDownloadedTracks,
  clearDiagnosticEvents,
  clearDiscoveryResults,
  clearSearchHistoryForScope,
  closeDestructiveConfirmation,
  closeHeaderSurfaces,
  closeLibraryOverlay,
  closeTipsOverlay,
  commandPaletteCommands,
  commandPaletteShortcutLabel,
  compactLyric,
  cookieAssuranceLine,
  cookieStatusLabel,
  cookieStatusTone,
  cookieSummaryLine,
  copyManualLyricsToClipboard,
  copyProfileLink,
  copyProfileShareCard,
  copySpotifyImportDebugLog,
  copyVaultSceneEmbed,
  currentManualLyricsLines,
  currentTrack,
  currentTrackSourceUrl,
  currentTrackTitle,
  cycleRepeatMode,
  desktopTopInsetClass,
  destructiveConfirmRequest,
  diagnosticPathBlockClass,
  diagnostics,
  diagnosticsApiBase,
  diagnosticsTopOffset,
  discardSearchHistoryItem,
  discordPrivate,
  discoveryItems,
  discoveryModeLabel,
  dismissRuntimeIssuePrompt,
  doodleIntensityBadge,
  doodleIntensityScale,
  downloadLabelById,
  downloadedTracks,
  draggedPlaylistName,
  draggedQueueIndex,
  dualVisualStageWidth,
  dualVisualStageZClass,
  engineStatus,
  exitVideoMode,
  expandedActiveRef,
  expandedContainerRef,
  experienceCenterInitialPage,
  faceControlSignal,
  faceControlStatus,
  faceVideoRef,
  favoriteInspectPlaylist,
  favoriteTracksList,
  ffmpegDetailLine,
  ffmpegStatusLabel,
  ffmpegStatusTone,
  flashLastAdded,
  focusedVaultName,
  focusedVaultTracks,
  focusedVaultVisibleTracks,
  formatBytes,
  formatDiagTime,
  formatManualLyricsTimestamp,
  formatTime,
  gestureNotice,
  getActivePlaybackPositionMs,
  getInspectSourceUrl,
  getProxyUrl,
  getTrackAddedMs,
  getTrackLastListenedMs,
  getTrackPlayCount,
  globalMediaShortcutsEnabled,
  handleAdd,
  handleAddToPlaylist,
  handleAttemptFixes,
  handleAvatarFileSelected,
  handleCleanVault,
  handleControl,
  handleCopyDiagnosticsValue,
  handleCopyPhrase,
  handleDeletePlaylist,
  handleDisableLock,
  handleDownloadCurrentTrack,
  handleDownloadMissingForVault,
  handleEnableLock,
  handleExportVault,
  handleFavoriteAddAll,
  handleFavoritePlayAll,
  handleGenerateRecoveryPhrase,
  handleGenerateSmartMix,
  handleHeaderDoubleClick,
  handleImportCookies,
  handleImportLocalMedia,
  handleImportSpotifyPlaylist,
  handleImportVault,
  handleLyricLineSeek,
  handleOfflineLibrarySearch,
  handlePlaylistAddAll,
  handlePlaylistPlayAll,
  handleRemove,
  handleRemoveFromPlaylist,
  handleRemoveTrackEverywhere,
  handleRemoveTrackFromPlaylist,
  handleRenamePlaylist,
  handleRepairEnvironment,
  handleResetLyricPreset,
  handleResetPlaybackEngine,
  handleResyncLyrics,
  handleRunInstaller,
  handleRunRuntimeRepair,
  handleSaveLyricPreset,
  handleSaveManualLyrics,
  handleSearch,
  handleSeek,
  handleSetSleepTimer,
  handleSync,
  handleToggleTouchIdLock,
  handleUpdateAction,
  handleVisualStagePointerActivity,
  handleVolumeChange,
  hasActiveSearchState,
  hasCompletedSearch,
  hasLyricPreset,
  headerAccentButtonClass,
  headerIconButtonClass,
  headerSearchInputRef,
  immersiveBeatIntensity,
  importReview,
  inferToastTone,
  inspectDurationMs,
  inspectPlaylistArtistCount,
  inspectPlaylistDurationMs,
  inspectPlaylistName,
  inspectPlaylistQueuedCount,
  inspectPlaylistSignal,
  inspectPlaylistTracklistText,
  inspectPlaylistTracks,
  inspectPrimaryTrack,
  inspectQueueIndex,
  inspectSourceUrl,
  inspectTarget,
  inspectTrack,
  inspectVaultNames,
  isAudioBuffering,
  isAuraMode,
  isAuraStageOpen,
  isAutoScrollPaused,
  isAutoplayEnabled,
  isAutoplayMenuOpen,
  isCameraPreviewVisible,
  isCommandPaletteOpen,
  isDepthMotionEnabled,
  isDiagnosticsOpen,
  isDoodleMode,
  isDownloadingTrack,
  isDualLayoutLocked,
  isDualVisualMode,
  isDualWorkspaceMode,
  isExperienceCenterOpen,
  isFaceControlEnabled,
  isFocusedMode,
  isFullDiscoveryContentReady,
  isFullPlaylistContentReady,
  isFullQueueContentReady,
  isGestureControlEnabled,
  isImmersiveLyricsLocked,
  isInspectPlaylistFromVault,
  isLibraryOverlayOpen,
  isLocalMediaImporting,
  isLockBusy,
  isLockModalOpen,
  isLyricPresetSaved,
  isLyricsExpanded,
  isLyricsLoading,
  isMacPlatform,
  isManualLyricsEditorOpen,
  isManualLyricsRawEditorOpen,
  isManualLyricsSaving,
  isManualLyricsTapMode,
  isMixtapeVaultContentReady,
  isMixtapeVaultOpen,
  isOfflineDownloadsBusy,
  isOfflineMode,
  isOfflineRemovalBusy,
  isPartyModeOpen,
  isPlayerOverlayOpen,
  isPlaying,
  isPlaylistInspect,
  isProfilePublishing,
  isQualityDropdownOpen,
  isRenamingPlaylist,
  isRuntimeRepairing,
  isSearchActive,
  isSearching,
  isSharedSceneOpen,
  isShortcutSettingsSaving,
  isSpotifyImportOpen,
  isSpotifyImporting,
  isStandalone,
  isStorageBusy,
  isTipsOverlayOpen,
  isTrackFavorite,
  isUpdateBusy,
  isVaultCleaning,
  isVaultImporting,
  isVerticalStack,
  isVideoReady,
  isViewingFavorites,
  isViewingFullDiscovery,
  isViewingFullPlaylist,
  isViewingFullQueue,
  lastAdded,
  leftWorkspaceClass,
  libraryActionTarget,
  libraryBrowseMode,
  libraryFilter,
  libraryInsights,
  libraryModeOptions,
  libraryOverlayCreateInputRef,
  libraryPlaylistFilterOptions,
  libraryPlaylistSortOptions,
  librarySearchNeedle,
  librarySearchTerm,
  librarySongFilter,
  librarySongFilterOptions,
  librarySongSort,
  librarySongSortOptions,
  librarySort,
  libraryTrackSort,
  libraryVisiblePlaylistNames,
  libraryVisibleSongEntries,
  livePulseReadout,
  loadManualLyricsFromRawText,
  localAudioRef,
  localVideoRef,
  lockDisablePassword,
  lockError,
  lockIdleMinutes,
  lockPasswordConfirm,
  lockPasswordInput,
  lockRecoveryStatus,
  lockRecoveryStatusError,
  lockStatus,
  lockUseTouchId,
  lyricOffsetMs,
  lyricPresetActionLabel,
  lyrics,
  lyricsContainerRef,
  lyricsHeaderEyebrow,
  lyricsListClass,
  lyricsPanelHeightClass,
  lyricsViewportClass,
  manualLyricsDraft,
  manualLyricsDraftError,
  manualLyricsRawText,
  manualLyricsSavedNotice,
  memoizedLyricsContent,
  mixtapeDurationMs,
  mixtapeEnergyPct,
  mixtapeLiveLyric,
  mixtapePositionMs,
  mixtapeProgressPct,
  mixtapePulse,
  mixtapePulseReadout,
  mixtapeSpectrum,
  mixtapeVaultRef,
  motion,
  movePlaylist,
  musicImportProvider,
  musicImportTheme,
  newPlaylistName,
  nextLyric,
  normalizeQueueTrack,
  normalizeTrackIdentity,
  oauthPrompt,
  offlineAvailableTracks,
  offlineDownloads,
  offlineLibrarySearchTerm,
  offlineVisibleTracks,
  openAppLockSettings,
  openDiagnosticsPage,
  openFeedbackPanel,
  openGestureLab,
  openLibraryOverlay,
  openManualLyricsEditor,
  openMusicImport,
  openPlaylistInspect,
  openSharedSceneInAether,
  openShortcutSettings,
  openSignalLedger,
  openTipsOverlay,
  openTrackInspect,
  orderedPlaylistNames,
  panelGlassClass,
  panelHeaderClass,
  panelInteractiveClass,
  parseInt,
  parseManualLyricsTimestamp,
  pasteCurrentLyricsIntoRawEditor,
  pendingLibraryItems,
  performanceMode,
  phraseBusy,
  phraseCopied,
  phraseGenerated,
  platform,
  playButtonRef,
  playDownloadedOnly,
  playInspectPlaylist,
  playSharedSceneInBrowser,
  playbackModeLabel,
  playerCardClass,
  playerTitleClass,
  playlists,
  profileStats,
  publishAetherProfile,
  pulseCanvasRef,
  qualityDropdownRef,
  queue,
  queueInspectPlaylist,
  queuePollDisplay,
  queuePollTime,
  refreshLockRecoveryStatus,
  refreshLockStatus,
  refreshOfflineDownloads,
  refreshStorageEstimate,
  refreshStorageStats,
  removeDownloadedById,
  removeManualLyricsDraftLine,
  renameValue,
  reorderPlaylistByDrag,
  reorderQueueByDrag,
  repairActionLabel,
  repairResult,
  repeatMode,
  repeatModeBadge,
  repeatModeLabel,
  requestDestructiveConfirmation,
  resetConfirmationSkipPrefs,
  resetShortcutSettingsToDefaults,
  resolveWarmupTrackId,
  rootModeClass,
  runAfterInputPaint,
  runStorageOptimize,
  runtimeIssuePrompt,
  saveProfileShareCard,
  saveShortcutSettings,
  searchHistoryByScope,
  searchQuery,
  searchResults,
  seekActivePlaybackTo,
  sessionRestoreNotice,
  setAetherProfile,
  setAuraPreset,
  setAutoplayMoodMode,
  setDiscordPrivate,
  setDraggedPlaylistName,
  setDraggedQueueIndex,
  setExperienceCenterInitialPage,
  setGlobalMediaShortcutsEnabled,
  setImportReview,
  setInspectTarget,
  setIsAppLocked,
  setIsAuraStageOpen,
  setIsAutoScrollPaused,
  setIsAutoplayEnabled,
  setIsAutoplayMenuOpen,
  setIsCameraPreviewVisible,
  setIsCommandPaletteOpen,
  setIsCreatingPlaylist,
  setIsDepthMotionEnabled,
  setIsDiagnosticsOpen,
  setIsDoodleMode,
  setIsExperienceCenterOpen,
  setIsFaceControlEnabled,
  setIsFocusedMode,
  setIsGestureControlEnabled,
  setIsLockModalOpen,
  setIsLyricsExpanded,
  setIsManualLyricsEditorOpen,
  setIsManualLyricsRawEditorOpen,
  setIsManualStop,
  setIsMixtapeVaultOpen,
  setIsOfflineMode,
  setIsPartyModeOpen,
  setIsPlayerOverlayOpen,
  setIsPlaying,
  setIsQualityDropdownOpen,
  setIsRenamingPlaylist,
  setIsSharedSceneOpen,
  setIsSpotifyImportOpen,
  setIsVerticalStack,
  setIsVideoReady,
  setIsViewingFullDiscovery,
  setIsViewingFullPlaylist,
  setIsViewingFullQueue,
  setLastAdded,
  setLibraryBrowseMode,
  setLibraryFilter,
  setLibrarySearchTerm,
  setLibrarySongFilter,
  setLibrarySongSort,
  setLibrarySort,
  setLibraryTrackSort,
  setLockDisablePassword,
  setLockIdleMinutes,
  setLockPasswordConfirm,
  setLockPasswordInput,
  setLockUseTouchId,
  setLyricOffsetMs,
  setManualLyricsRawText,
  setMusicImportProvider,
  setNewPlaylistName,
  setOauthPrompt,
  setOfflineLibrarySearchTerm,
  setPartyInfo,
  setPerformanceMode,
  setQueue,
  setRenameValue,
  setSearchQuery,
  setShortcutDraft,
  setShortcutSettingsError,
  setShowShortcutHints,
  setSkipEvents,
  setSleepCustomMinutes,
  setSleepFadeEnabled,
  setSpotifyImportLogs,
  setSpotifyImportPlaylistName,
  setSpotifyImportProgress,
  setSpotifyImportUrl,
  setStopAfterTrack,
  setStoragePolicy,
  setTipsDontShowAgain,
  setVideoMode,
  setVideoQuality,
  setViewingPlaylist,
  setVisualControlsPinned,
  setVisualVideoFit,
  setVisualizerMode,
  setWebAudioUnlocked,
  sharedModalCloseButtonClass,
  sharedScene,
  sharedSceneCanPlay,
  shortcutDraft,
  shortcutLabel,
  shortcutSettingsError,
  shortcuts,
  showFavoriteLibraryCard,
  showImmersiveLyricsOverlay,
  showSecondaryColumn,
  showShortcutHints,
  showVisualLyricOverlay,
  showVisualStage,
  showWindowsHeaderWindowControls,
  showWindowsTitleStrip,
  skipEvents,
  skipReasonToast,
  sleepCustomMinutes,
  sleepDeadline,
  sleepFadeEnabled,
  sleepRemainingStr,
  sleepTimerControlsRef,
  sleepTimerValue,
  soundLedgerView,
  spotifyImportLogs,
  spotifyImportPlaylistName,
  spotifyImportProgress,
  spotifyImportUrl,
  stampManualLyricsDraftLine,
  stopAfterTrack,
  storageEstimate,
  storagePolicy,
  storageStats,
  switchVideoMode,
  systemStats,
  themeColor,
  tipsDontShowAgain,
  toReadableShortcut,
  toggleFavoriteTrack,
  toggleWindowMaximize,
  topHeaderClass,
  trackControlAccent,
  trackControlGlow,
  trackHasSavedLyrics,
  trackProgressAccent,
  trackProgressGlow,
  unpublishAetherProfile,
  updateActionLabel,
  updateInfo,
  updateManualLyricsDraftLine,
  updateToast,
  vaultPulse,
  videoMode,
  videoQuality,
  viewingPlaylist,
  visualControlsPinned,
  visualLyricOverlayBottomClass,
  visualStageFooterVisible,
  visualStageHeaderVisible,
  visualStageLyric,
  visualStageNextLyric,
  visualStageTitle,
  visualStageTitleMarquee,
  visualVideoFit,
  visualizerCanvasRef,
  visualizerMode,
  volume,
  volumeToast,
  webAudioUnlocked,
  workspaceModeLabel,
  youtubeAuthRequiredRef,
  youtubePlayerRef,
  ytDlpDetailLine,
  ytDlpStatusLabel,
  ytDlpStatusTone
};
}
