name: Disabled Auto Version Push

on:
  workflow_dispatch:


jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
    - name: Auto push disabled
      run: echo "Auto version commit/push workflow is intentionally disabled."
